name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Checks out your repository so the workflow can access it

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # Set up Docker Buildx to support advanced build features

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        # Logs in to Docker Hub using secrets stored in GitHub

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/your-image-name .
          docker push your-dockerhub-username/your-image-name
        # Builds the Docker image and pushes it to Docker Hub

      - name: Deploy to Vercel
        run: |
          npm i -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        # Installs the Vercel CLI and deploys the application to Vercel
